### ISSUE TITLE
Error: No module named 'utils.loggy'

### ISSUE THREAD

**Issue by Tiny-Stark** [Praveensenpai/bumsBot#2]
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "C:\Users\Opiq\Desktop\1\bumsBot\main.py", line 6, in <module>
    from bums.bums import Bums
  File "C:\Users\Opiq\Desktop\1\bumsBot\bums\bums.py", line 9, in <module>
    from telegram.client import TGClient
  File "C:\Users\Opiq\Desktop\1\bumsBot\telegram\client.py", line 14, in <module>
    from utils.loggy import logger
ModuleNotFoundError: No module named 'utils.loggy'

**Comment by Praveensenpai** [comment]
Did u run
uv sync --python 3.13
???

**Comment by Praveensenpai** [comment]
Are u inside a bumsBot directory?

**Comment by Tiny-Stark** [comment]
PS C:\Users\Opiq\Desktop\1\bumsBot> uv sync --python 3.13
>>
Resolved 28 packages in 31ms
error: Failed to prepare distributions
  Caused by: Failed to download and build `tgcrypto==1.2.5`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit code: 1)

[stdout]
running bdist_wheel
running build
running build_py
copying tests\__init__.py -> build\lib.win32-cpython-313\tests
copying tests\cbc\test_cbc.py -> build\lib.win32-cpython-313\tests\cbc
copying tests\cbc\__init__.py -> build\lib.win32-cpython-313\tests\cbc
copying tests\ctr\test_ctr.py -> build\lib.win32-cpython-313\tests\ctr
copying tests\ctr\__init__.py -> build\lib.win32-cpython-313\tests\ctr
copying tests\ige\test_ige.py -> build\lib.win32-cpython-313\tests\ige
copying tests\ige\__init__.py -> build\lib.win32-cpython-313\tests\ige
running build_ext
building 'tgcrypto' extension
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Opiq\AppData\Local\uv\cache\builds-v0\.tmpBKH9NU\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files\Windows Kits\10\include\10.0.10240.0\ucrt" /Tctgcrypto/aes256.c /Fobuild\temp.win32-cpython-313\Release\tgcrypto/aes256.obj
aes256.c
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Opiq\AppData\Local\uv\cache\builds-v0\.tmpBKH9NU\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files\Windows Kits\10\include\10.0.10240.0\ucrt" /Tctgcrypto/cbc256.c /Fobuild\temp.win32-cpython-313\Release\tgcrypto/cbc256.obj
cbc256.c
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Opiq\AppData\Local\uv\cache\builds-v0\.tmpBKH9NU\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files\Windows Kits\10\include\10.0.10240.0\ucrt" /Tctgcrypto/ctr256.c /Fobuild\temp.win32-cpython-313\Release\tgcrypto/ctr256.obj
ctr256.c
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Opiq\AppData\Local\uv\cache\builds-v0\.tmpBKH9NU\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files\Windows Kits\10\include\10.0.10240.0\ucrt" /Tctgcrypto/ige256.c /Fobuild\temp.win32-cpython-313\Release\tgcrypto/ige256.obj
ige256.c
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Opiq\AppData\Local\uv\cache\builds-v0\.tmpBKH9NU\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\include -IC:\Users\Opiq\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86-none\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files\Windows Kits\10\include\10.0.10240.0\ucrt" /Tctgcrypto/tgcrypto.c /Fobuild\temp.win32-cpython-313\Release\tgcrypto/tgcrypto.obj
tgcrypto.c
c:\users\opiq\appdata\roaming\uv\python\cpython-3.13.0-windows-x86-none\include\pyconfig.h(238): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory

[stderr]
C:\Users\Opiq\AppData\Local\uv\cache\builds-v0\.tmpBKH9NU\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit code 2
PS C:\Users\Opiq\Desktop\1\bumsBot>

**Comment by Praveensenpai** [comment]
I haven't tested on windows OS. Will ping u after test.

**Comment by Praveensenpai** [comment]
https://github.com/pyrogram/tgcrypto/issues/37

**Comment by Praveensenpai** [comment]
you can try now I changed some dependency hope it works~

**Comment by Praveensenpai** [comment]
now 

reclone the repo 
and
use uv sync instead of uv sync --python 3.13
and uv run main.py

**Comment by Tiny-Stark** [comment]
thanks for your update
it's running but there an error

2024-11-13 16:01:10 | ERROR - An unexpected error occurred: 'data'
2024-11-13 16:01:10 | ERROR - Traceback (most recent call last):
  File "C:\Users\Opiq\Desktop\1\bumsBot\main.py", line 40, in daily_singin_task
    await bums.daily_sign()
  File "C:\Users\Opiq\Desktop\1\bumsBot\bums\bums.py", line 166, in daily_sign
    if resp and resp.json()["data"]["msg"] == "OK":
                ~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

but after that it's running till now
is it ok?

**Comment by Praveensenpai** [comment]
Give me some minutes I'll look into it

**Comment by Praveensenpai** [comment]
try now reclone repo and try it now. I added more print statement so I can debug.

**Comment by Tiny-Stark** [comment]
ERROR - {'code': 0, 'msg': 'OK', 'data': {'lists': [{'days': 1, 'daysDesc': 'Day 1', 'normal': 10000, 'premium': 0, 'status': 1, 'adId': 0, 'bigDay': 0}, {'days': 2, 'daysDesc': 'Day 2', 'normal': 20000, 'premium': 0, 'status': 0, 'adId': 0, 'bigDay': 0}, {'days': 3, 'daysDesc': 'Day 3', 'normal': 30000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 4, 'daysDesc': 'Day 4', 'normal': 40000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 5, 'daysDesc': 'Day 5', 'normal': 50000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 6, 'daysDesc': 'Day 6', 'normal': 60000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 7, 'daysDesc': 'Day 7', 'normal': 80000, 'premium': 200010001, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 8, 'daysDesc': 'Day 8', 'normal': 100000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 9, 'daysDesc': 'Day 9', 'normal': 200000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 10, 'daysDesc': 'Day 10', 'normal': 300000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 11, 'daysDesc': 'Day 11', 'normal': 400000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 12, 'daysDesc': 'Day 12', 'normal': 500000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 13, 'daysDesc': 'Day 13', 'normal': 600000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 14, 'daysDesc': 'Day 14', 'normal': 800000, 'premium': 200010002, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 15, 'daysDesc': 'Day 15', 'normal': 1000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 16, 'daysDesc': 'Day 16', 'normal': 2000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 17, 'daysDesc': 'Day 17', 'normal': 3000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 18, 'daysDesc': 'Day 18', 'normal': 4000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 19, 'daysDesc': 'Day 19', 'normal': 5000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 20, 'daysDesc': 'Day 20', 'normal': 6000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 21, 'daysDesc': 'Day 21', 'normal': 8000000, 'premium': 200010003, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 22, 'daysDesc': 'Day 22', 'normal': 10000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 23, 'daysDesc': 'Day 23', 'normal': 20000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 24, 'daysDesc': 'Day 24', 'normal': 30000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 25, 'daysDesc': 'Day 25', 'normal': 40000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 26, 'daysDesc': 'Day 26', 'normal': 50000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 27, 'daysDesc': 'Day 27', 'normal': 60000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 28, 'daysDesc': 'Day 28', 'normal': 80000000, 'premium': 200010004, 'status': 2, 'adId': 0, 'bigDay': 1}], 'signNum': 2, 'signStatus': 0}}

**Comment by Praveensenpai** [comment]
can u give me full log?

**Comment by primushkodenis** [comment]
`PS D:\bums\2> uv run main.py
2024-11-14 12:42:31 | INFO - SLEEP DELAY SET TO 30 MINUTES
Welcome to Pyrogram (version 2.0.106)
Pyrogram is free software and comes with ABSOLUTELY NO WARRANTY. Licensed
under the terms of the GNU Lesser General Public License v3.0 (LGPL-3.0).

The confirmation code has been sent via Telegram app
Enter confirmation code: 
2024-11-14 12:43:28 | SUCCESS - Logged in as @Deni
2024-11-14 12:43:28 | SUCCESS - Logged in successfully

2024-11-14 12:43:29 | INFO - Getting user information...


2024-11-14 12:43:32 | INFO - ========== Denis ==========
2024-11-14 12:43:32 | INFO - ID: 185113

2024-11-14 12:43:32 | INFO - Balance: 11.9K

2024-11-14 12:43:32 | INFO - Profit per hour: 0B

2024-11-14 12:43:32 | INFO - Level: 1
2024-11-14 12:43:32 | INFO - Energy Level: 1
2024-11-14 12:43:32 | INFO - Energy: 2.0K
2024-11-14 12:43:32 | INFO - ===Daily Sign-in task started===
2024-11-14 12:43:35 | WARNING - Failed to claim daily reward
2024-11-14 12:43:35 | ERROR - {'code': 0, 'msg': 'OK', 'data': {'lists': [{'days': 1, 'daysDesc': 'Day 1', 'normal': 10000, 'premium': 0, 'status': 0, 'adId': 0, 'bigDay': 0}, {'days': 2, 'daysDesc': 'Day 2', 'normal': 20000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 3, 'daysDesc': 'Day 3', 'normal': 30000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 4, 'daysDesc': 'Day 4', 'normal': 40000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 5, 'daysDesc': 'Day 5', 'normal': 50000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 6, 'daysDesc': 'Day 6', 'normal': 60000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 7, 'daysDesc': 'Day 7', 'normal': 80000, 'premium': 200010001, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 8, 'daysDesc': 'Day 8', 'normal': 100000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 9, 'daysDesc': 'Day 9', 'normal': 200000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 10, 'daysDesc': 'Day 10', 'normal': 300000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 11, 'daysDesc': 'Day 11', 'normal': 400000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 12, 'daysDesc': 'Day 12', 'normal': 500000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 13, 'daysDesc': 'Day 13', 'normal': 600000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 14, 'daysDesc': 'Day 14', 'normal': 800000, 'premium': 200010002, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 15, 'daysDesc': 'Day 15', 'normal': 1000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 16, 'daysDesc': 'Day 16', 'normal': 2000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 17, 'daysDesc': 'Day 17', 'normal': 3000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 18, 'daysDesc': 'Day 18', 'normal': 4000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 19, 'daysDesc': 'Day 19', 'normal': 5000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 20, 'daysDesc': 'Day 20', 'normal': 6000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 21, 'daysDesc': 'Day 21', 'normal': 8000000, 'premium': 200010003, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 22, 'daysDesc': 'Day 22', 'normal': 10000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 23, 'daysDesc': 'Day 23', 'normal': 20000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 24, 'daysDesc': 'Day 24', 'normal': 30000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 25, 'daysDesc': 'Day 25', 'normal': 40000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 26, 'daysDesc': 'Day 26', 'normal': 50000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 27, 'daysDesc': 'Day 27', 'normal': 60000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 28, 'daysDesc': 'Day 28', 'normal': 80000000, 'premium': 200010004, 'status': 2, 'adId': 0, 'bigDay': 1}], 'signNum': 1, 'signStatus': 0}}


2024-11-14 12:43:38 | INFO - ===Tap task started===
2024-11-14 12:43:42 | SUCCESS - Tap successful


2024-11-14 12:43:45 | INFO - ===Process Upgrades task started===
2024-11-14 12:43:48 | INFO - Processing multiple upgrades...
2024-11-14 12:43:49 | INFO - Total Eligible Minelist: 1
2024-11-14 12:43:49 | INFO - Upgrading mine 101 to level 1
2024-11-14 12:43:52 | SUCCESS - Upgraded mine 101 successfully
2024-11-14 12:43:52 | INFO - Upgrade successful! Remaining Money: 23650
2024-11-14 12:44:52 | INFO - Processing multiple upgrades...
2024-11-14 12:44:53 | INFO - Total Eligible Minelist: 2
2024-11-14 12:44:53 | INFO - Upgrading mine 106 to level 1
2024-11-14 12:44:56 | SUCCESS - Upgraded mine 106 successfully
2024-11-14 12:44:56 | INFO - Upgrade successful! Remaining Money: 22652
2024-11-14 12:44:56 | INFO - Upgrading mine 101 to level 2
2024-11-14 12:45:00 | SUCCESS - Upgraded mine 101 successfully
2024-11-14 12:45:00 | INFO - Upgrade successful! Remaining Money: 21652
2024-11-14 12:46:00 | INFO - Processing multiple upgrades...
2024-11-14 12:46:01 | INFO - Total Eligible Minelist: 4
2024-11-14 12:46:01 | INFO - Upgrading mine 102 to level 1
2024-11-14 12:46:04 | SUCCESS - Upgraded mine 102 successfully
2024-11-14 12:46:04 | INFO - Upgrade successful! Remaining Money: 21059
2024-11-14 12:46:04 | INFO - Upgrading mine 111 to level 1
2024-11-14 12:46:07 | SUCCESS - Upgraded mine 111 successfully
2024-11-14 12:46:07 | INFO - Upgrade successful! Remaining Money: 19559
2024-11-14 12:46:07 | INFO - Upgrading mine 101 to level 3
2024-11-14 12:46:11 | SUCCESS - Upgraded mine 101 successfully
2024-11-14 12:46:11 | INFO - Upgrade successful! Remaining Money: 18059
2024-11-14 12:46:11 | INFO - Upgrading mine 106 to level 2
2024-11-14 12:46:14 | SUCCESS - Upgraded mine 106 successfully
2024-11-14 12:46:14 | INFO - Upgrade successful! Remaining Money: 16059
2024-11-14 12:47:14 | INFO - Processing multiple upgrades...
2024-11-14 12:47:15 | INFO - Total Eligible Minelist: 5
2024-11-14 12:47:15 | INFO - Upgrading mine 107 to level 1
2024-11-14 12:47:18 | SUCCESS - Upgraded mine 107 successfully
2024-11-14 12:47:18 | INFO - Upgrade successful! Remaining Money: 14980
2024-11-14 12:47:18 | INFO - Upgrading mine 102 to level 2
2024-11-14 12:47:21 | SUCCESS - Upgraded mine 102 successfully
2024-11-14 12:47:21 | INFO - Upgrade successful! Remaining Money: 13780
2024-11-14 12:47:21 | INFO - Upgrading mine 116 to level 1
2024-11-14 12:47:25 | SUCCESS - Upgraded mine 116 successfully
2024-11-14 12:47:25 | INFO - Upgrade successful! Remaining Money: 11780
2024-11-14 12:47:25 | INFO - Upgrading mine 111 to level 2
2024-11-14 12:47:28 | SUCCESS - Upgraded mine 111 successfully
2024-11-14 12:47:28 | INFO - Upgrade successful! Remaining Money: 8780
2024-11-14 12:47:28 | INFO - Upgrading mine 106 to level 3
2024-11-14 12:47:31 | SUCCESS - Upgraded mine 106 successfully
2024-11-14 12:47:31 | INFO - Upgrade successful! Remaining Money: 5580
2024-11-14 12:48:31 | INFO - Processing multiple upgrades...
2024-11-14 12:48:33 | INFO - Total Eligible Minelist: 7
2024-11-14 12:48:33 | INFO - Upgrading mine 103 to level 1
2024-11-14 12:48:37 | SUCCESS - Upgraded mine 103 successfully
2024-11-14 12:48:37 | INFO - Upgrade successful! Remaining Money: 4929
2024-11-14 12:48:37 | INFO - Upgrading mine 112 to level 1
2024-11-14 12:48:40 | SUCCESS - Upgraded mine 112 successfully
2024-11-14 12:48:40 | INFO - Upgrade successful! Remaining Money: 3329
2024-11-14 12:48:40 | INFO - Upgrading mine 107 to level 2
2024-11-14 12:48:43 | SUCCESS - Upgraded mine 107 successfully
2024-11-14 12:48:43 | INFO - Upgrade successful! Remaining Money: 1129
2024-11-14 12:48:43 | INFO - Not enough money to upgrade mine 101.
2024-11-14 12:48:43 | INFO - Not enough money to upgrade mine 121.
2024-11-14 12:48:43 | INFO - Not enough money to upgrade mine 116.
2024-11-14 12:48:43 | INFO - Not enough money to upgrade mine 111.
2024-11-14 12:49:43 | INFO - Processing multiple upgrades...
2024-11-14 12:49:44 | INFO - Total Eligible Minelist: 7
2024-11-14 12:49:44 | INFO - No more money available to upgrade
2024-11-14 12:49:44 | INFO - Lets take a rest for 30 minutes`

**Comment by Tiny-Stark** [comment]
> can u give me full log?

It doesn't seems tobe appearing anymore, maybe because I had sign-in it manually, I'll try it again tomorrow

**Comment by Praveensenpai** [comment]
Yea sure. I'll also try it; maybe it's problem with the api or not, not sure.

**Comment by Praveensenpai** [comment]
fixed

**Comment by Tiny-Stark** [comment]
Activating virtual environment...
Starting the bot...
2024-11-15 15:05:31 | INFO - SLEEP DELAY SET TO 8.513565891472869 MINUTES
2024-11-15 15:05:41 | SUCCESS - Logged in as @Codotbelek
2024-11-15 15:05:42 | SUCCESS - Logged in successfully

2024-11-15 15:05:42 | INFO - Getting user information...


2024-11-15 15:05:45 | INFO - ========== Codot📦 Bums ==========
2024-11-15 15:05:45 | INFO - ID: 1856313881991229440

2024-11-15 15:05:45 | INFO - Balance: 59.6K


2024-11-15 15:05:45 | INFO - Profit per hour: 515.5K
2024-11-15 15:05:45 | INFO - Level: 6
2024-11-15 15:05:45 | INFO - Energy Level: 18
2024-11-15 15:05:45 | INFO - Energy: 106.0K
2024-11-15 15:05:45 | INFO - ===Daily Sign-in task started===
2024-11-15 15:05:49 | ERROR - An unexpected error occurred: 'data'

2024-11-15 15:05:49 | ERROR - Traceback (most recent call last):
  File "C:\Users\Opiq\Desktop\1\bumsBot\main.py", line 40, in daily_singin_task
    await bums.daily_sign()
  File "C:\Users\Opiq\Desktop\1\bumsBot\bums\bums.py", line 166, in daily_sign
    if resp and resp.json()["data"]["msg"] == "OK":
                ~~~~~~~~~~~^^^^^^^^
KeyError: 'data'


2024-11-15 15:05:49 | INFO - ===Tap task started===
2024-11-15 15:05:52 | SUCCESS - Tap successful


2024-11-15 15:05:55 | INFO - ===Process Upgrades task started===
2024-11-15 15:05:58 | INFO - Processing multiple upgrades...
2024-11-15 15:05:58 | INFO - Total Eligible Minelist: 20
2024-11-15 15:05:58 | INFO - No more money available to upgrade
2024-11-15 15:05:58 | INFO - Lets take a rest for 8 minutes, 30 seconds

Still

**Comment by Praveensenpai** [comment]
did u reclone the repo? I changed the code a bit so ....

**Comment by Tiny-Stark** [comment]
Yes I did, git pull before running.
I opened new issue since this is different matter
