### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by primushkodenis** [Praveensenpai/bumsBot#5]
The confirmation code has been sent via Telegram app
Enter confirmation code: 
2024-11-14 13:42:16 | SUCCESS - Logged in as @Vikt
Task exception was never retrieved
future: <Task finished name='Task-91' coro=<Client.handle_updates() done, defined at D:\Bums\8\.venv\Lib\site-packages\pyrogram\client.py:535> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "D:\Bums\8\.venv\Lib\site-packages\pyrogram\client.py", line 540, in handle_updates
    await self.fetch_peers(updates.users),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bums\8\.venv\Lib\site-packages\pyrogram\client.py", line 531, in fetch_peers
    await self.storage.update_peers(parsed_peers)
  File "D:\Bums\8\.venv\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 129, in update_peers
    self.conn.executemany(
sqlite3.ProgrammingError: Cannot operate on a closed database.

**Comment by Praveensenpai** [comment]
This error from pyrogram side. The program will restart itself so no need to worry.
