### ISSUE TITLE
Sign-in not working

### ISSUE THREAD

**Issue by Tiny-Stark** [Praveensenpai/bumsBot#6]
Activating virtual environment...
Starting the bot...
2024-11-15 15:05:31 | INFO - SLEEP DELAY SET TO 8.513565891472869 MINUTES
2024-11-15 15:05:41 | SUCCESS - Logged in as @Codotbelek
2024-11-15 15:05:42 | SUCCESS - Logged in successfully

2024-11-15 15:05:42 | INFO - Getting user information...

2024-11-15 15:05:45 | INFO - ========== Codot📦 Bums ==========
2024-11-15 15:05:45 | INFO - ID: 1856313881991229440

2024-11-15 15:05:45 | INFO - Balance: 59.6K

2024-11-15 15:05:45 | INFO - Profit per hour: 515.5K
2024-11-15 15:05:45 | INFO - Level: 6
2024-11-15 15:05:45 | INFO - Energy Level: 18
2024-11-15 15:05:45 | INFO - Energy: 106.0K
2024-11-15 15:05:45 | INFO - ===Daily Sign-in task started===
2024-11-15 15:05:49 | ERROR - An unexpected error occurred: 'data'

2024-11-15 15:05:49 | ERROR - Traceback (most recent call last):
  File "C:\Users\Opiq\Desktop\1\bumsBot\main.py", line 40, in daily_singin_task
    await bums.daily_sign()
  File "C:\Users\Opiq\Desktop\1\bumsBot\bums\bums.py", line 166, in daily_sign
    if resp and resp.json()["data"]["msg"] == "OK":
                ~~~~~~~~~~~^^^^^^^^
KeyError: 'data'


2024-11-15 15:05:49 | INFO - ===Tap task started===
2024-11-15 15:05:52 | SUCCESS - Tap successful


2024-11-15 15:05:55 | INFO - ===Process Upgrades task started===
2024-11-15 15:05:58 | INFO - Processing multiple upgrades...
2024-11-15 15:05:58 | INFO - Total Eligible Minelist: 20
2024-11-15 15:05:58 | INFO - No more money available to upgrade
2024-11-15 15:05:58 | INFO - Lets take a rest for 8 minutes, 30 seconds

**Comment by Praveensenpai** [comment]
u probably using a old code. try reclone the repo and run.

**Comment by Tiny-Stark** [comment]
Oops my bad, I forgot to stash edited main.py🙏🏻

**Comment by Praveensenpai** [comment]
No worries 👍
